//+------------------------------------------------------------------+
//|                                                   EABuilderPro.mq5 |
//|                                      Generated by EA Builder Pro   |
//+------------------------------------------------------------------+
#property copyright "EA Builder Pro"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>
CTrade trade;

//--- Global Indicator Handles
int handle_1;
int handle_2;

//--- Input parameters
//--- Moving Average Parameters
input int Inp_1_period = 50; // period
input string Inp_1_method = MODE_MODE_SMA; // method
input int Inp_1_shift = 0; // shift
input string Inp_1_applied_price = PRICE_PRICE_CLOSE; // applied_price
//--- Moving Average Parameters
input int Inp_2_period = 200; // period
input string Inp_2_method = MODE_MODE_SMA; // method
input int Inp_2_shift = 0; // shift
input string Inp_2_applied_price = PRICE_PRICE_CLOSE; // applied_price
//--- Action: Buy Market
input double Inp_4_lots = 0.1; // lots

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   handle_1 = iMA(_Symbol, _Period, Inp_1_period, 0, MODE_SMA, PRICE_CLOSE);
   handle_2 = iMA(_Symbol, _Period, Inp_2_period, 0, MODE_SMA, PRICE_CLOSE);
   return(INIT_SUCCEEDED);
  }
  
void OnDeinit(const int reason) {}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   double buf_1[];
   ArraySetAsSeries(buf_1, true);
   if(CopyBuffer(handle_1, 0, 0, 3, buf_1) <= 0) return;

   double buf_2[];
   ArraySetAsSeries(buf_2, true);
   if(CopyBuffer(handle_2, 0, 0, 3, buf_2) <= 0) return;

   bool cond_3 = false;

   if (cond_3) {
      if (PositionsTotal() == 0) trade.Buy(Inp_4_lots);
   }
  }
//+------------------------------------------------------------------+