import { app, BrowserWindow } from 'electron';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import log from 'electron-log';
import pkg from 'electron-updater';
const { autoUpdater } = pkg;

const __dirname = path.dirname(fileURLToPath(import.meta.url));

process.env.APP_ROOT = path.join(__dirname, '..');

export const VITE_DEV_SERVER_URL = process.env['VITE_DEV_SERVER_URL'];
export const MAIN_DIST = path.join(process.env.APP_ROOT, 'dist-electron');
export const RENDERER_DIST = path.join(process.env.APP_ROOT, 'dist');

process.env.VITE_PUBLIC = VITE_DEV_SERVER_URL ? path.join(process.env.APP_ROOT, 'public') : RENDERER_DIST;

let win;

function createWindow() {
  win = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: true,
      contextIsolation: false, // For simplicity in MVP, in prod use context bridge
    },
    titleBarStyle: 'hidden',
    titleBarOverlay: {
      color: '#1e1e24',
      symbolColor: '#ffffff',
    },
    backgroundColor: '#121212'
  });

  if (VITE_DEV_SERVER_URL) {
    win.loadURL(VITE_DEV_SERVER_URL);
  } else {
    win.loadFile(path.join(RENDERER_DIST, 'index.html'));
  }
}

// Auto-Updater Configuration
autoUpdater.logger = log;
autoUpdater.logger.transports.file.level = 'info';
autoUpdater.autoDownload = true;
autoUpdater.autoInstallOnAppQuit = true;

// Auto-updater will automatically use app-update.yml generated by electron-builder for GitHub releases

log.info('App starting...');

autoUpdater.on('checking-for-update', () => {
  log.info('Checking for update...');
});
autoUpdater.on('update-available', (info) => {
  log.info('Update available.');
  if (win) win.webContents.send('update-available', info);
});
autoUpdater.on('update-not-available', (info) => {
  log.info('Update not available.');
  if (win) win.webContents.send('update-not-available', info);
});
autoUpdater.on('error', (err) => {
  log.info('Error in auto-updater. ' + err);
  if (win) win.webContents.send('updater-error', err.message);
});
autoUpdater.on('download-progress', (progressObj) => {
  let log_message = "Download speed: " + progressObj.bytesPerSecond;
  log_message = log_message + ' - Downloaded ' + progressObj.percent + '%';
  log_message = log_message + ' (' + progressObj.transferred + "/" + progressObj.total + ')';
  log.info(log_message);
  if (win) win.webContents.send('download-progress', progressObj);
});
autoUpdater.on('update-downloaded', (info) => {
  log.info('Update downloaded');
  if (win) win.webContents.send('update-downloaded', info);
  // Optional: autoUpdater.quitAndInstall();
});

import { ipcMain, dialog } from 'electron';
import fs from 'fs';

ipcMain.handle('save-ea-file', async (event, { content, defaultPath = 'MyExpert.mq5', extension = 'mq5' }) => {
  const { canceled, filePath } = await dialog.showSaveDialog(win, {
    title: 'Save Expert Advisor',
    defaultPath: defaultPath,
    filters: [
      { name: `MQL${extension === 'mq5' ? '5' : '4'} Source File`, extensions: [extension] }
    ]
  });

  if (canceled || !filePath) {
    return { success: false, reason: 'canceled' };
  }

  try {
    fs.writeFileSync(filePath, content);
    return { success: true, filePath };
  } catch (err) {
    return { success: false, reason: err.message };
  }
});

import crypto from 'crypto';

ipcMain.handle('hash-data', async (event, { data }) => {
  try {
    // Advanced SHA-256 Hashing for extra security as requested
    const hash = crypto.createHash('sha256').update(data).digest('hex');
    return { success: true, hash };
  } catch (err) {
    return { success: false, reason: err.message };
  }
});

import https from 'https';
import http from 'http';

ipcMain.handle('fetch-url', async (event, { url }) => {
  return new Promise((resolve) => {
    try {
      const client = url.startsWith('https') ? https : http;
      client.get(url, (res) => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => resolve({ success: true, data }));
      }).on('error', err => resolve({ success: false, reason: err.message }));
    } catch (err) {
      resolve({ success: false, reason: err.message });
    }
  });
});

ipcMain.handle('select-csv-file', async () => {
  const { canceled, filePaths } = await dialog.showOpenDialog(win, {
    title: 'Select MT5 Historical Data',
    properties: ['openFile'],
    filters: [
      { name: 'CSV Files', extensions: ['csv', 'txt'] }
    ]
  });
  if (canceled || filePaths.length === 0) return { success: false };
  return { success: true, filePath: filePaths[0], fileName: path.basename(filePaths[0]) };
});

ipcMain.handle('read-file', async (event, { filePath }) => {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return { success: true, content };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

import { safeStorage } from 'electron';

ipcMain.handle('secure-set', async (event, { value }) => {
  if (safeStorage.isEncryptionAvailable()) {
    try {
      const buffer = safeStorage.encryptString(value);
      return { success: true, encrypted: buffer.toString('hex') };
    } catch (err) {
      return { success: false, error: err.message };
    }
  }
  return { success: false, error: 'Encryption not available' };
});

ipcMain.handle('secure-get', async (event, { encryptedHex }) => {
  if (safeStorage.isEncryptionAvailable() && encryptedHex) {
    try {
      const buffer = Buffer.from(encryptedHex, 'hex');
      const decrypted = safeStorage.decryptString(buffer);
      return { success: true, decrypted };
    } catch (err) {
      return { success: false, error: err.message };
    }
  }
  return { success: false, error: 'Decryption failed or not available' };
});

ipcMain.handle('save-keys', async (event, keys) => {
  try {
    const configPath = path.join(app.getPath('userData'), 'api_keys.json');
    let dataToSave = {};
    if (safeStorage.isEncryptionAvailable()) {
       for (const [k, v] of Object.entries(keys)) {
         if (v) dataToSave[k] = safeStorage.encryptString(v).toString('hex');
       }
       dataToSave._encrypted = true;
    } else {
       dataToSave = { ...keys, _encrypted: false };
    }
    fs.writeFileSync(configPath, JSON.stringify(dataToSave));
    return { success: true };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

ipcMain.handle('load-keys', async () => {
  try {
    const configPath = path.join(app.getPath('userData'), 'api_keys.json');
    if (!fs.existsSync(configPath)) return { success: true, keys: {} };
    const data = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    const keys = {};
    if (data._encrypted && safeStorage.isEncryptionAvailable()) {
       for (const [k, v] of Object.entries(data)) {
         if (k !== '_encrypted' && v) {
            try {
              keys[k] = safeStorage.decryptString(Buffer.from(v, 'hex'));
            } catch (e) {
              // Ignore invalid decryptions
            }
         }
       }
    } else {
       for (const [k, v] of Object.entries(data)) {
         if (k !== '_encrypted') keys[k] = v;
       }
    }
    return { success: true, keys };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
    win = null;
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.whenReady().then(() => {
  createWindow();
  
  // Check for updates shortly after startup
  setTimeout(() => {
    autoUpdater.checkForUpdatesAndNotify();
  }, 3000);
});

ipcMain.on('restart_app', () => {
  autoUpdater.quitAndInstall();
});

ipcMain.handle('check-for-updates', async () => {
  try {
    const result = await autoUpdater.checkForUpdates();
    return { success: true, message: 'Checking for updates...' };
  } catch (err) {
    return { success: false, error: err.message };
  }
});
