export function generateMQL4(nodes, edges) {
  const actions = nodes.filter(n => n.type === 'action');
  const indicators = nodes.filter(n => n.type === 'indicator');
  const logics = nodes.filter(n => n.type === 'logic');
  const timeframes = nodes.filter(n => n.type === 'timeframe');
  const grids = nodes.filter(n => n.type === 'grid');
  const partialCloses = nodes.filter(n => n.type === 'partialClose');
  const newsFilters = nodes.filter(n => n.type === 'newsFilter');
  const drawdowns = nodes.filter(n => n.type === 'drawdown');
  const tradeManagements = nodes.filter(n => n.type === 'tradeManagement');
  const licenses = nodes.filter(n => n.type === 'license');
  const customCodes = nodes.filter(n => n.type === 'customCode');

  let code = `//+------------------------------------------------------------------+
//|                                                   EABuilderPro.mq4 |
//|                                      Generated by EA Builder Pro   |
//+------------------------------------------------------------------+
#property copyright "EA Builder Pro"
#property link      ""
#property version   "1.00"
#property strict

//--- Input parameters
`;

  customCodes.filter(c => c.data.params?.location === 'Global').forEach(c => {
    code += `//--- Custom Global Code\n`;
    code += `${c.data.params?.code || ''}\n\n`;
  });

  // Generate Inputs
  indicators.forEach((ind) => {
    code += `//--- ${ind.data.name} Parameters\n`;
    if (ind.data.params) {
      Object.keys(ind.data.params).forEach(paramKey => {
        const val = ind.data.params[paramKey];
        const type = typeof val === 'number' ? 'int' : 'string';
        let formattedVal = type === 'string' ? `"${val}"` : val;
        
        if (paramKey === 'method') formattedVal = `MODE_${val}`;
        if (paramKey === 'applied_price' || paramKey === 'applied_volume') formattedVal = `PRICE_${val.toUpperCase()}`;
        
        code += `extern ${type} Inp_${ind.id}_${paramKey} = ${formattedVal}; // ${paramKey}\n`;
      });
    }
  });

  actions.forEach((action) => {
    if (action.type === 'alert') {
      code += `//--- Alert: ${action.data.alertType || 'Popup Alert'}\n`;
      code += `extern string Inp_${action.id}_Message = "${action.data.message || 'Signal Triggered!'}"; // Alert Message\n`;
    } else {
      code += `//--- Action: ${action.data.action}\n`;
      if (action.data.params) {
        Object.keys(action.data.params).forEach(paramKey => {
           code += `extern double Inp_${action.id}_${paramKey} = ${action.data.params[paramKey]}; // ${paramKey}\n`;
        });
      } else if (action.data.lots) {
         code += `extern double Inp_${action.id}_lots = ${action.data.lots}; // Lot Size\n`;
      }
    }
  });

  grids.forEach((grid) => {
    code += `//--- Grid / Martingale Settings\n`;
    code += `extern double Inp_Grid_${grid.id}_Multiplier = ${grid.data.multiplier || 2.0}; // Lot Multiplier\n`;
    code += `extern int Inp_Grid_${grid.id}_Step = ${grid.data.step || 20}; // Step in Points\n`;
  });

  drawdowns.forEach((dd) => {
    code += `//--- Drawdown Protector\n`;
    code += `extern double Inp_DD_${dd.id}_MaxDD = ${dd.data.maxDrawdown || 5.0}; // Max Drawdown (%)\n`;
  });

  tradeManagements.forEach((tm) => {
    code += `//--- Trade Management\n`;
    code += `extern int Inp_TM_${tm.id}_Trailing = ${tm.data.trailingStop || 20}; // Trailing Stop (Points)\n`;
    code += `extern int Inp_TM_${tm.id}_BreakEven = ${tm.data.breakEven || 15}; // Break Even Activation (Points)\n`;
  });

  partialCloses.forEach(pc => {
    code += `//--- Partial Close Settings\n`;
    code += `extern int Inp_${pc.id}_TriggerPips = ${pc.data.triggerPips || 50}; // Trigger (Pips)\n`;
    code += `extern int Inp_${pc.id}_ClosePercent = ${pc.data.closePercent || 50}; // Close (%) \n`;
  });

  newsFilters.forEach(nf => {
    code += `//--- News Filter Settings\n`;
    code += `extern int Inp_News_${nf.id}_MinsBefore = ${nf.data.minsBefore || 30}; // Stop before News (Mins)\n`;
    code += `extern int Inp_News_${nf.id}_MinsAfter = ${nf.data.minsAfter || 30}; // Resume after News (Mins)\n`;
  });

  code += `
//--- Indicator Helper Functions
`;

  // Generate Helper functions for indicators
  indicators.forEach(ind => {
    const symbolStr = ind.data.symbol && ind.data.symbol !== 'Current' ? `"${ind.data.symbol}"` : 'Symbol()';
    const tfStr = ind.data.timeframe && ind.data.timeframe !== 'Current' ? `PERIOD_${ind.data.timeframe}` : '0';

    code += `double GetInd_${ind.id}(int shift) {\n`;

    if (ind.data.isCustom) {
      let paramsArr = [];
      if (ind.data.schema) {
        ind.data.schema.forEach(field => {
          let val = ind.data.params[field.name];
          if (field.type === 'string' || field.type === 'select') val = `"${val}"`;
          paramsArr.push(val);
        });
      }
      code += `   return iCustom(${symbolStr}, ${tfStr}, "${ind.data.name}"${paramsArr.length > 0 ? ', ' + paramsArr.join(', ') : ''}, 0, shift);\n`;
    } else {
      const cfg = INDICATORS_CONFIG[ind.data.indicatorId];
      if (cfg && cfg.mql4_init) {
        let fn = cfg.mql4_init;
        fn = fn.replace('Symbol()', symbolStr);
        fn = fn.replace('0', tfStr); // assuming default timeframes use '0'
        
        if (ind.data.schema) {
          ind.data.schema.forEach(field => {
            fn = fn.replace(field.name, ind.data.params[field.name]);
          });
        }
        // mql4_init usually has shift as the last param or hardcoded.
        // let's ensure it has shift. The INDICATORS_CONFIG mql4_init usually has ', 0)' or ', shift)'
        fn = fn.replace(/,\s*0\)$/, ', shift)');
        code += `   return ${fn};\n`;
      } else {
        code += `   return 0.0; // Unsupported indicator\n`;
      }
    }
    code += `}\n\n`;
  });

  code += `
//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
`;

  licenses.forEach(lic => {
     code += `   //--- License Protection\n`;
     if (lic.data.params?.accountNumber) {
        code += `   if(AccountNumber() != ${lic.data.params.accountNumber}) {\n`;
        code += `      Alert("License Error: Invalid Account Number!");\n`;
        code += `      return(INIT_FAILED);\n`;
        code += `   }\n`;
     }
     if (lic.data.params?.expiryDate) {
        const d = lic.data.params.expiryDate;
        code += `   if(TimeCurrent() > StringToTime("${d}")) {\n`;
        code += `      Alert("License Error: EA Expired!");\n`;
        code += `      return(INIT_FAILED);\n`;
        code += `   }\n`;
     }
  });

  customCodes.filter(c => c.data.params?.location === 'OnInit').forEach(c => {
    code += `   //--- Custom Code (OnInit)\n`;
    code += `   ${c.data.params?.code?.split('\n').join('\n   ') || ''}\n\n`;
  });

  code += `
   return(INIT_SUCCEEDED);
  }
  
void OnDeinit(const int reason) {}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
`;

  customCodes.filter(c => c.data.params?.location === 'OnTick').forEach(c => {
    code += `   //--- Custom Code (OnTick)\n`;
    code += `   ${c.data.params?.code?.split('\n').join('\n   ') || ''}\n\n`;
  });

  if (drawdowns.length > 0) {
    const dd = drawdowns[0];
    code += `   //--- Drawdown Protection
   double balance = AccountBalance();
   double equity = AccountEquity();
   if (balance > 0 && ((balance - equity) / balance * 100.0) >= Inp_DD_${dd.id}_MaxDD) {
      Print("Max Drawdown Reached! Closing all trades.");
      for(int i=OrdersTotal()-1; i>=0; i--) {
         if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
            if(OrderType() == OP_BUY) OrderClose(OrderTicket(), OrderLots(), Bid, 3, clrRed);
            else if(OrderType() == OP_SELL) OrderClose(OrderTicket(), OrderLots(), Ask, 3, clrRed);
         }
      }
      return; // Stop processing further ticks
   }
`;
   }

  if (tradeManagements.length > 0) {
    const tm = tradeManagements[0];
    code += `
   //--- Trade Management (Trailing Stop & Break Even)
   if (Inp_TM_${tm.id}_Trailing > 0 || Inp_TM_${tm.id}_BreakEven > 0) {
      for(int i=OrdersTotal()-1; i>=0; i--) {
         if (OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
            double openPrice = OrderOpenPrice();
            double currentSL = OrderStopLoss();
            double currentTP = OrderTakeProfit();
            int type = OrderType();
            
            if (type == OP_BUY) {
               // Break Even
               if (Inp_TM_${tm.id}_BreakEven > 0 && Bid - openPrice >= Inp_TM_${tm.id}_BreakEven * Point) {
                  if (currentSL < openPrice) OrderModify(OrderTicket(), openPrice, openPrice, currentTP, 0, clrGreen);
               }
               // Trailing Stop
               if (Inp_TM_${tm.id}_Trailing > 0 && Bid - openPrice >= Inp_TM_${tm.id}_Trailing * Point) {
                  double newSL = Bid - Inp_TM_${tm.id}_Trailing * Point;
                  if (currentSL < newSL || currentSL == 0) OrderModify(OrderTicket(), openPrice, newSL, currentTP, 0, clrGreen);
               }
            } else if (type == OP_SELL) {
               // Break Even
               if (Inp_TM_${tm.id}_BreakEven > 0 && openPrice - Ask >= Inp_TM_${tm.id}_BreakEven * Point) {
                  if (currentSL > openPrice || currentSL == 0) OrderModify(OrderTicket(), openPrice, openPrice, currentTP, 0, clrRed);
               }
               // Trailing Stop
               if (Inp_TM_${tm.id}_Trailing > 0 && openPrice - Ask >= Inp_TM_${tm.id}_Trailing * Point) {
                  double newSL = Ask + Inp_TM_${tm.id}_Trailing * Point;
                  if (currentSL > newSL || currentSL == 0) OrderModify(OrderTicket(), openPrice, newSL, currentTP, 0, clrRed);
               }
            }
         }
      }
   }
`;
  }

  if (partialCloses.length > 0) {
    code += `
    // Partial Close Logic
    for(int i = OrdersTotal() - 1; i >= 0; i--) {
       if (OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
          if (OrderSymbol() == Symbol()) {
             double profitPips = 0;
             double openPrice = OrderOpenPrice();
             
             if(OrderType() == OP_BUY) {
                profitPips = (Bid - openPrice) / Point;
             } else if(OrderType() == OP_SELL) {
                profitPips = (openPrice - Ask) / Point;
             }
             
             if (profitPips >= Inp_${partialCloses[0].id}_TriggerPips) {
                double volToClose = OrderLots() * (Inp_${partialCloses[0].id}_ClosePercent / 100.0);
                volToClose = NormalizeDouble(volToClose, 2);
                if (volToClose >= MarketInfo(Symbol(), MODE_MINLOT)) {
                   if(OrderType() == OP_BUY) {
                      OrderClose(OrderTicket(), volToClose, Bid, 3, clrGreen);
                   } else if(OrderType() == OP_SELL) {
                      OrderClose(OrderTicket(), volToClose, Ask, 3, clrRed);
                   }
                }
             }
          }
       }
    }
    `;
  }


  // Evaluate logics
  logics.forEach(logic => {
    const edgeIn1 = edges.find(e => e.target === logic.id && e.targetHandle === 'in1');
    const edgeIn2 = edges.find(e => e.target === logic.id && e.targetHandle === 'in2');
    
    let val1 = edgeIn1 ? `GetInd_${edgeIn1.source}(1)` : '0.0';
    let val2 = edgeIn2 ? `GetInd_${edgeIn2.source}(1)` : '0.0';
    
    let prevVal1 = edgeIn1 ? `GetInd_${edgeIn1.source}(2)` : '0.0';
    let prevVal2 = edgeIn2 ? `GetInd_${edgeIn2.source}(2)` : '0.0';

    const op = logic.data.operator;
    let condition = 'false';

    if (op === 'Crosses Above') condition = `(${val1} > ${val2} && ${prevVal1} <= ${prevVal2})`;
    else if (op === 'Crosses Below') condition = `(${val1} < ${val2} && ${prevVal1} >= ${prevVal2})`;
    else if (op === '>') condition = `(${val1} > ${val2})`;
    else if (op === '<') condition = `(${val1} < ${val2})`;
    else if (op === '=') condition = `(${val1} == ${val2})`;

    code += `   bool cond_${logic.id} = ${condition};\n`;
  });

  // Evaluate Timeframes
  timeframes.forEach(tf => {
    let tfCond = 'true';
    if (tf.data.session) {
      if (tf.data.session === 'London') {
        tfCond = `(TimeHour(TimeCurrent()) >= 8 && TimeHour(TimeCurrent()) < 16)`;
      } else if (tf.data.session === 'New York') {
        tfCond = `(TimeHour(TimeCurrent()) >= 13 && TimeHour(TimeCurrent()) < 22)`;
      } else if (tf.data.session === 'Tokyo') {
        tfCond = `(TimeHour(TimeCurrent()) >= 0 && TimeHour(TimeCurrent()) < 9)`;
      } else if (tf.data.session === 'Custom') {
        const startH = parseInt(tf.data.startHour.split(':')[0] || '0');
        const endH = parseInt(tf.data.endHour.split(':')[0] || '23');
        tfCond = `(TimeHour(TimeCurrent()) >= ${startH} && TimeHour(TimeCurrent()) < ${endH})`;
      }
    }
    code += `   bool cond_time_${tf.id} = ${tfCond};\n`;
  });

  // Evaluate actions
  actions.forEach(action => {
    const connectingEdge = edges.find(e => e.target === action.id);
    let conditionCode = connectingEdge ? `cond_${connectingEdge.source}` : 'true';

    let timeCondition = '';
    timeframes.forEach(tf => {
       timeCondition += ` && cond_time_${tf.id}`;
    });
    
    let newsCondition = '';
    newsFilters.forEach(nf => {
       newsCondition += ` && !CheckNews(Inp_News_${nf.id}_MinsBefore, Inp_News_${nf.id}_MinsAfter)`;
    });
    
    conditionCode += timeCondition + newsCondition;

    const actType = action.data.action;
    const lotVar = `Inp_${action.id}_lots`;
    const distVar = `Inp_${action.id}_distance`;

    code += `\n   if (${conditionCode}) {\n`;
    
    if (action.type === 'alert') {
      if (action.data.alertType === 'Push Notification') {
         code += `      SendNotification(Inp_${action.id}_Message);\n`;
      } else if (action.data.alertType === 'Print to Journal') {
         code += `      Print(Inp_${action.id}_Message);\n`;
      } else {
         code += `      Alert(Inp_${action.id}_Message);\n`;
      }
    } else {
      if (actType === 'Buy Market' || actType === 'Buy') {
         code += `      if (OrdersTotal() == 0) OrderSend(Symbol(), OP_BUY, ${lotVar}, Ask, 3, 0, 0, "EA Builder", 0, 0, clrGreen);\n`;
      } else if (actType === 'Sell Market' || actType === 'Sell') {
         code += `      if (OrdersTotal() == 0) OrderSend(Symbol(), OP_SELL, ${lotVar}, Bid, 3, 0, 0, "EA Builder", 0, 0, clrRed);\n`;
      } else if (actType === 'Buy Limit') {
         code += `      double price = Ask - (${distVar} * Point);\n`;
         code += `      OrderSend(Symbol(), OP_BUYLIMIT, ${lotVar}, price, 3, 0, 0, "EA Builder", 0, 0, clrBlue);\n`;
      } else if (actType === 'Sell Limit') {
         code += `      double price = Bid + (${distVar} * Point);\n`;
         code += `      OrderSend(Symbol(), OP_SELLLIMIT, ${lotVar}, price, 3, 0, 0, "EA Builder", 0, 0, clrRed);\n`;
      } else if (actType === 'Buy Stop') {
         code += `      double price = Ask + (${distVar} * Point);\n`;
         code += `      OrderSend(Symbol(), OP_BUYSTOP, ${lotVar}, price, 3, 0, 0, "EA Builder", 0, 0, clrBlue);\n`;
      } else if (actType === 'Sell Stop') {
         code += `      double price = Bid - (${distVar} * Point);\n`;
         code += `      OrderSend(Symbol(), OP_SELLSTOP, ${lotVar}, price, 3, 0, 0, "EA Builder", 0, 0, clrRed);\n`;
      }
    }
    
    code += `   }\n`;
  });

  if (grids.length > 0) {
    const grid = grids[0];
    code += `
   //--- Grid / Martingale Recovery Logic (Simplified)
   if (OrdersTotal() > 0) {
      if (OrderSelect(OrdersTotal() - 1, SELECT_BY_POS, MODE_TRADES)) {
         double openPrice = OrderOpenPrice();
         double currentPrice = OrderType() == OP_BUY ? Bid : Ask;
         double profit = OrderProfit();
         
         if (profit < 0 && MathAbs(openPrice - currentPrice) / Point >= Inp_Grid_${grid.id}_Step) {
            double newLot = OrderLots() * Inp_Grid_${grid.id}_Multiplier;
            if (OrderType() == OP_BUY) {
               OrderSend(Symbol(), OP_BUY, newLot, Ask, 3, 0, 0, "EA Builder Grid", 0, 0, clrGreen);
            } else if (OrderType() == OP_SELL) {
               OrderSend(Symbol(), OP_SELL, newLot, Bid, 3, 0, 0, "EA Builder Grid", 0, 0, clrRed);
            }
         }
       }
    }
    
//+------------------------------------------------------------------+
//| News Filter Stub Function                                        |
//| Replace this logic with your ForexFactory/Economic Calendar code |
//+------------------------------------------------------------------+
bool CheckNews(int minsBefore, int minsAfter) {
   // To be implemented by user or connected via WebRequest
   // Returns true if there is High Impact news currently.
   return false;
}
`;
  }

  code += `  }
//+------------------------------------------------------------------+`;

  return code;
}
