export function generateIndMQL4(nodes, edges, projectName) {
  const name = projectName.replace(/[^a-zA-Z0-9_]/g, '_');
  let code = `//+------------------------------------------------------------------+
//|                                                      ${name}.mq4 |
//|                        Generated by AI EA Builder (Indicator)    |
//+------------------------------------------------------------------+
#property copyright "AI EA Builder"
#property link      "https://github.com"
#property version   "1.00"
#property indicator_chart_window
`;

  const buffers = nodes.filter(n => n.type === 'buffer');
  
  if (buffers.length > 0) {
     code += `#property indicator_buffers ${buffers.length}\n`;
  } else {
     code += `#property indicator_buffers 1\n`;
  }

  // Define properties for each buffer
  buffers.forEach((b, idx) => {
      code += `\n//--- plot Buffer${b.data.bufferId}\n`;
      code += `#property indicator_color${idx + 1}  ${b.data.color || 'clrRed'}\n`;
      // Note: MQL4 handles style slightly differently in init() but we can set properties too
  });

  code += `\n//--- indicator buffers\n`;
  buffers.forEach(b => {
      code += `double         Buffer${b.data.bufferId}[];\n`;
  });

  const indicators = nodes.filter(n => n.type === 'indicator');
  
  // Inputs
  indicators.forEach(ind => {
    code += `\n//--- ${ind.data.name} Settings\n`;
    const params = ind.data.params || {};
    Object.keys(params).forEach(k => {
      const val = params[k];
      const type = typeof val === 'number' ? (val % 1 !== 0 ? 'double' : 'int') : 'string';
      const safeVal = type === 'string' ? `"${val}"` : val;
      code += `extern ${type} Inp_${ind.id}_${k} = ${safeVal}; // ${k}\n`;
    });
  });

  // OnInit
  code += `
//+------------------------------------------------------------------+
//| Custom indicator initialization function                         |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- indicator buffers mapping
`;
  
  buffers.forEach((b, idx) => {
     code += `   SetIndexBuffer(${idx}, Buffer${b.data.bufferId});\n`;
     
     let style = 'DRAW_LINE';
     if (b.data.style === 'DRAW_HISTOGRAM') style = 'DRAW_HISTOGRAM';
     if (b.data.style === 'DRAW_ARROW') style = 'DRAW_ARROW';
     code += `   SetIndexStyle(${idx}, ${style});\n`;
  });

  code += `
   return(INIT_SUCCEEDED);
}
`;

  // OnCalculate
  code += `
//+------------------------------------------------------------------+
//| Custom indicator iteration function                              |
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < 10) return(0);
   int limit = rates_total - prev_calculated;
   if(prev_calculated > 0) limit++;
   else limit = rates_total - 1;

   for(int i=0; i<limit; i++) {
`;

  // Logic linking
  buffers.forEach(b => {
      const connectedEdge = edges.find(e => e.target === b.id);
      if (connectedEdge) {
          const sourceId = connectedEdge.source;
          const sourceInd = indicators.find(ind => ind.id === sourceId);
          if (sourceInd) {
              const isCustom = sourceInd.data.isCustom;
              if (isCustom) {
                  let args = `Symbol(), 0, "${sourceInd.data.name}"`;
                  const params = sourceInd.data.params || {};
                  Object.keys(params).forEach(k => {
                     args += `, Inp_${sourceInd.id}_${k}`;
                  });
                  args += `, 0, i`; // mode 0, shift i
                  code += `      Buffer${b.data.bufferId}[i] = iCustom(${args});\n`;
              } else {
                  // Standard iMA placeholder
                  let args = `Symbol(), 0, 14, 0, MODE_SMA, PRICE_CLOSE, i`;
                  code += `      Buffer${b.data.bufferId}[i] = iMA(${args});\n`;
              }
          } else {
             code += `      Buffer${b.data.bufferId}[i] = 0.0;\n`;
          }
      }
  });

  code += `   }
   return(rates_total);
}
//+------------------------------------------------------------------+
`;

  return code;
}
