export function generateMQL5(nodes, edges) {
  const actions = nodes.filter(n => n.type === 'action');
  const indicators = nodes.filter(n => n.type === 'indicator');
  const logics = nodes.filter(n => n.type === 'logic');
  const timeframes = nodes.filter(n => n.type === 'timeframe');
  const grids = nodes.filter(n => n.type === 'grid');
  const partialCloses = nodes.filter(n => n.type === 'partialClose');
  const newsFilters = nodes.filter(n => n.type === 'newsFilter');
  const drawdowns = nodes.filter(n => n.type === 'drawdown');
  const tradeManagements = nodes.filter(n => n.type === 'tradeManagement');
  const licenses = nodes.filter(n => n.type === 'license');
  const customCodes = nodes.filter(n => n.type === 'customCode');

  let code = `//+------------------------------------------------------------------+
//|                                                   EABuilderPro.mq5 |
//|                                      Generated by EA Builder Pro   |
//+------------------------------------------------------------------+
#property copyright "EA Builder Pro"
#property link      ""
#property version   "1.00"

#include <Trade\\Trade.mqh>
CTrade trade;

//--- Global Indicator Handles
`;

  customCodes.filter(c => c.data.params?.location === 'Global').forEach(c => {
    code += `//--- Custom Global Code\n`;
    code += `${c.data.params?.code || ''}\n\n`;
  });

  indicators.forEach(ind => {
    code += `int handle_${ind.id};\n`;
  });

  code += `\n//--- Input parameters\n`;

  // Generate Inputs
  indicators.forEach((ind) => {
    code += `//--- ${ind.data.name} Parameters\n`;
    if (ind.data.params) {
      Object.keys(ind.data.params).forEach(paramKey => {
        const val = ind.data.params[paramKey];
        const type = typeof val === 'number' ? 'int' : 'string';
        let formattedVal = type === 'string' ? `"${val}"` : val;
        
        if (paramKey === 'method') formattedVal = `MODE_${val}`;
        if (paramKey === 'applied_price' || paramKey === 'applied_volume') formattedVal = `PRICE_${val.toUpperCase()}`;
        
        code += `input ${type} Inp_${ind.id}_${paramKey} = ${formattedVal}; // ${paramKey}\n`;
      });
    }
  });

  actions.forEach((action) => {
    if (action.type === 'alert') {
      code += `//--- Alert: ${action.data.alertType || 'Popup Alert'}\n`;
      code += `input string Inp_${action.id}_Message = "${action.data.message || 'Signal Triggered!'}"; // Alert Message\n`;
    } else {
      code += `//--- Action: ${action.data.action}\n`;
      if (action.data.params) {
        Object.keys(action.data.params).forEach(paramKey => {
           code += `input double Inp_${action.id}_${paramKey} = ${action.data.params[paramKey]}; // ${paramKey}\n`;
        });
      } else if (action.data.lots) {
         code += `input double Inp_${action.id}_lots = ${action.data.lots}; // Lot Size\n`;
      }
    }
  });

  grids.forEach((grid) => {
    code += `//--- Grid / Martingale Settings\n`;
    code += `input double Inp_Grid_${grid.id}_Multiplier = ${grid.data.multiplier || 2.0}; // Lot Multiplier\n`;
    code += `input int Inp_Grid_${grid.id}_Step = ${grid.data.step || 20}; // Step in Points\n`;
  });

  drawdowns.forEach((dd) => {
    code += `//--- Drawdown Protector\n`;
    code += `input double Inp_DD_${dd.id}_MaxDD = ${dd.data.maxDrawdown || 5.0}; // Max Drawdown (%)\n`;
  });

  tradeManagements.forEach((tm) => {
    code += `//--- Trade Management\n`;
    code += `input int Inp_TM_${tm.id}_Trailing = ${tm.data.trailingStop || 20}; // Trailing Stop (Points)\n`;
    code += `input int Inp_TM_${tm.id}_BreakEven = ${tm.data.breakEven || 15}; // Break Even Activation (Points)\n`;
  });

  partialCloses.forEach(pc => {
    code += `//--- Partial Close Settings\n`;
    code += `input int Inp_${pc.id}_TriggerPips = ${pc.data.triggerPips || 50}; // Trigger (Pips)\n`;
    code += `input int Inp_${pc.id}_ClosePercent = ${pc.data.closePercent || 50}; // Close (%) \n`;
  });

  newsFilters.forEach(nf => {
    code += `//--- News Filter Settings\n`;
    code += `input int Inp_News_${nf.id}_MinsBefore = ${nf.data.minsBefore || 30}; // Stop trading before News (Mins)\n`;
    code += `input int Inp_News_${nf.id}_MinsAfter = ${nf.data.minsAfter || 30}; // Resume trading after News (Mins)\n`;
  });

  code += `
//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
`;

  licenses.forEach(lic => {
     code += `   //--- License Protection\n`;
     if (lic.data.params?.accountNumber) {
        code += `   if(AccountInfoInteger(ACCOUNT_LOGIN) != ${lic.data.params.accountNumber}) {\n`;
        code += `      Alert("License Error: Invalid Account Number!");\n`;
        code += `      return(INIT_FAILED);\n`;
        code += `   }\n`;
     }
     if (lic.data.params?.expiryDate) {
        const d = lic.data.params.expiryDate;
        code += `   if(TimeCurrent() > StringToTime("${d}")) {\n`;
        code += `      Alert("License Error: EA Expired!");\n`;
        code += `      return(INIT_FAILED);\n`;
        code += `   }\n`;
     }
  });

  customCodes.filter(c => c.data.params?.location === 'OnInit').forEach(c => {
    code += `   //--- Custom Code (OnInit)\n`;
    code += `   ${c.data.params?.code?.split('\n').join('\n   ') || ''}\n\n`;
  });

  // Initialize Handles
  indicators.forEach(ind => {
    const symbolStr = ind.data.symbol && ind.data.symbol !== 'Current' ? `"${ind.data.symbol}"` : '_Symbol';
    const tfStr = ind.data.timeframe && ind.data.timeframe !== 'Current' ? `PERIOD_${ind.data.timeframe}` : 'PERIOD_CURRENT';

    if (ind.data.isCustom) {
      code += `\n   // Init custom indicator: ${ind.data.name}\n`;
      let paramsArr = [];
      if (ind.data.schema) {
        ind.data.schema.forEach(field => {
          let val = ind.data.params[field.name];
          if (field.type === 'string' || field.type === 'select') val = `"${val}"`;
          paramsArr.push(val);
        });
      }
      code += `   handle_${ind.id} = iCustom(${symbolStr}, ${tfStr}, "${ind.data.name}"${paramsArr.length > 0 ? ', ' + paramsArr.join(', ') : ''});\n`;
    } else {
      const cfg = INDICATORS_CONFIG[ind.data.indicatorId];
      if (cfg && cfg.mql5_init) {
        let fn = cfg.mql5_init;
        fn = fn.replace('_Symbol', symbolStr);
        fn = fn.replace('PERIOD_CURRENT', tfStr);
        if (ind.data.schema) {
          ind.data.schema.forEach(field => {
            fn = fn.replace(field.name, ind.data.params[field.name]);
          });
        }
        code += `   handle_${ind.id} = ${fn};\n`;
      }
    }
  });

  code += `   return(INIT_SUCCEEDED);
  }
  
void OnDeinit(const int reason) {}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
`;

  customCodes.filter(c => c.data.params?.location === 'OnTick').forEach(c => {
    code += `   //--- Custom Code (OnTick)\n`;
    code += `   ${c.data.params?.code?.split('\n').join('\n   ') || ''}\n\n`;
  });

  if (drawdowns.length > 0) {
    const dd = drawdowns[0];
    code += `   //--- Drawdown Protection
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   if (balance > 0 && ((balance - equity) / balance * 100.0) >= Inp_DD_${dd.id}_MaxDD) {
      // Close all positions logic here (simplified)
      Print("Max Drawdown Reached! Closing all trades.");
      for(int i=PositionsTotal()-1; i>=0; i--) {
         ulong ticket = PositionGetTicket(i);
         trade.PositionClose(ticket);
      }
      return; // Stop processing further ticks
   }
`;
   }

  if (tradeManagements.length > 0) {
    const tm = tradeManagements[0];
    code += `
   //--- Trade Management (Trailing Stop & Break Even)
   if (Inp_TM_${tm.id}_Trailing > 0 || Inp_TM_${tm.id}_BreakEven > 0) {
      for(int i=PositionsTotal()-1; i>=0; i--) {
         ulong ticket = PositionGetTicket(i);
         if (PositionSelectByTicket(ticket)) {
            double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
            double currentSL = PositionGetDouble(POSITION_SL);
            double currentTP = PositionGetDouble(POSITION_TP);
            long type = PositionGetInteger(POSITION_TYPE);
            double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
            double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
            double point = _Point;

            if (type == POSITION_TYPE_BUY) {
               // Break Even
               if (Inp_TM_${tm.id}_BreakEven > 0 && bid - openPrice >= Inp_TM_${tm.id}_BreakEven * point) {
                  if (currentSL < openPrice) trade.PositionModify(ticket, openPrice, currentTP);
               }
               // Trailing Stop
               if (Inp_TM_${tm.id}_Trailing > 0 && bid - openPrice >= Inp_TM_${tm.id}_Trailing * point) {
                  double newSL = bid - Inp_TM_${tm.id}_Trailing * point;
                  if (currentSL < newSL || currentSL == 0) trade.PositionModify(ticket, newSL, currentTP);
               }
            } else if (type == POSITION_TYPE_SELL) {
               // Break Even
               if (Inp_TM_${tm.id}_BreakEven > 0 && openPrice - ask >= Inp_TM_${tm.id}_BreakEven * point) {
                  if (currentSL > openPrice || currentSL == 0) trade.PositionModify(ticket, openPrice, currentTP);
               }
               // Trailing Stop
               if (Inp_TM_${tm.id}_Trailing > 0 && openPrice - ask >= Inp_TM_${tm.id}_Trailing * point) {
                  double newSL = ask + Inp_TM_${tm.id}_Trailing * point;
                  if (currentSL > newSL || currentSL == 0) trade.PositionModify(ticket, newSL, currentTP);
               }
            }
         }
      }
   }
`;
  }

  if (partialCloses.length > 0) {
    const pc = partialCloses[0];
    code += `
   // Partial Close Logic
   for(int i = PositionsTotal() - 1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0 && PositionSelectByTicket(ticket)) {
         double profitPips = 0;
         double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
         double currentPrice = PositionGetDouble(POSITION_PRICE_CURRENT);
         long posType = PositionGetInteger(POSITION_TYPE);
         double currentVolume = PositionGetDouble(POSITION_VOLUME);
         
         if(posType == POSITION_TYPE_BUY) {
            profitPips = (currentPrice - openPrice) / _Point;
         } else if(posType == POSITION_TYPE_SELL) {
            profitPips = (openPrice - currentPrice) / _Point;
         }
         
         if (profitPips >= Inp_${pc.id}_TriggerPips) {
            double volToClose = currentVolume * (Inp_${pc.id}_ClosePercent / 100.0);
            volToClose = NormalizeDouble(volToClose, 2);
            if (volToClose > 0.01) {
               trade.PositionClosePartial(ticket, volToClose);
            }
         }
      }
   }
`;
  }

  // Copy buffers for indicators
  indicators.forEach(ind => {
    code += `   double buf_${ind.id}[];\n`;
    code += `   ArraySetAsSeries(buf_${ind.id}, true);\n`;
    code += `   if(CopyBuffer(handle_${ind.id}, 0, 0, 3, buf_${ind.id}) <= 0) return;\n\n`;
  });

  // Evaluate logics
  logics.forEach(logic => {
    const edgeIn1 = edges.find(e => e.target === logic.id && e.targetHandle === 'in1');
    const edgeIn2 = edges.find(e => e.target === logic.id && e.targetHandle === 'in2');
    
    let val1 = edgeIn1 ? `buf_${edgeIn1.source}[1]` : '0.0';
    let val2 = edgeIn2 ? `buf_${edgeIn2.source}[1]` : '0.0';
    
    let prevVal1 = edgeIn1 ? `buf_${edgeIn1.source}[2]` : '0.0';
    let prevVal2 = edgeIn2 ? `buf_${edgeIn2.source}[2]` : '0.0';

    const op = logic.data.operator;
    let condition = 'false';

    if (op === 'Crosses Above') condition = `(${val1} > ${val2} && ${prevVal1} <= ${prevVal2})`;
    else if (op === 'Crosses Below') condition = `(${val1} < ${val2} && ${prevVal1} >= ${prevVal2})`;
    else if (op === '>') condition = `(${val1} > ${val2})`;
    else if (op === '<') condition = `(${val1} < ${val2})`;
    else if (op === '=') condition = `(${val1} == ${val2})`;

    code += `   bool cond_${logic.id} = ${condition};\n`;
  });

  // Evaluate Timeframes
  timeframes.forEach(tf => {
    let tfCond = 'true';
    if (tf.data.session) {
      if (tf.data.session === 'London') {
        tfCond = `(TimeHour(TimeCurrent()) >= 8 && TimeHour(TimeCurrent()) < 16)`;
      } else if (tf.data.session === 'New York') {
        tfCond = `(TimeHour(TimeCurrent()) >= 13 && TimeHour(TimeCurrent()) < 22)`;
      } else if (tf.data.session === 'Tokyo') {
        tfCond = `(TimeHour(TimeCurrent()) >= 0 && TimeHour(TimeCurrent()) < 9)`;
      } else if (tf.data.session === 'Custom') {
        const startH = parseInt(tf.data.startHour.split(':')[0] || '0');
        const endH = parseInt(tf.data.endHour.split(':')[0] || '23');
        tfCond = `(TimeHour(TimeCurrent()) >= ${startH} && TimeHour(TimeCurrent()) < ${endH})`;
      }
    }
    code += `   bool cond_time_${tf.id} = ${tfCond};\n`;
  });

  // Evaluate actions
  actions.forEach(action => {
    const connectingEdge = edges.find(e => e.target === action.id);
    let conditionCode = connectingEdge ? `cond_${connectingEdge.source}` : 'true';

    let timeCondition = '';
    timeframes.forEach(tf => {
       timeCondition += ` && cond_time_${tf.id}`;
    });
    
    let newsCondition = '';
    newsFilters.forEach(nf => {
       newsCondition += ` && !CheckNews(Inp_News_${nf.id}_MinsBefore, Inp_News_${nf.id}_MinsAfter)`;
    });
    
    conditionCode += timeCondition + newsCondition;

    const actType = action.data.action;
    const lotVar = `Inp_${action.id}_lots`;
    const distVar = `Inp_${action.id}_distance`;

    code += `\n   if (${conditionCode}) {\n`;
    
    if (action.type === 'alert') {
      if (action.data.alertType === 'Push Notification') {
         code += `      SendNotification(Inp_${action.id}_Message);\n`;
      } else if (action.data.alertType === 'Print to Journal') {
         code += `      Print(Inp_${action.id}_Message);\n`;
      } else {
         code += `      Alert(Inp_${action.id}_Message);\n`;
      }
    } else {
      if (actType === 'Buy Market' || actType === 'Buy') {
         code += `      if (PositionsTotal() == 0) trade.Buy(${lotVar});\n`;
      } else if (actType === 'Sell Market' || actType === 'Sell') {
         code += `      if (PositionsTotal() == 0) trade.Sell(${lotVar});\n`;
      } else if (actType === 'Buy Limit') {
         code += `      double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK) - (${distVar} * _Point);\n`;
         code += `      trade.BuyLimit(${lotVar}, price);\n`;
      } else if (actType === 'Sell Limit') {
         code += `      double price = SymbolInfoDouble(_Symbol, SYMBOL_BID) + (${distVar} * _Point);\n`;
         code += `      trade.SellLimit(${lotVar}, price);\n`;
      } else if (actType === 'Buy Stop') {
         code += `      double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK) + (${distVar} * _Point);\n`;
         code += `      trade.BuyStop(${lotVar}, price);\n`;
      } else if (actType === 'Sell Stop') {
         code += `      double price = SymbolInfoDouble(_Symbol, SYMBOL_BID) - (${distVar} * _Point);\n`;
         code += `      trade.SellStop(${lotVar}, price);\n`;
      }
    }
    
    code += `   }\n`;
  });

  if (grids.length > 0) {
    const grid = grids[0];
    code += `
   //--- Grid / Martingale Recovery Logic (Simplified)
   if (PositionsTotal() > 0) {
      ulong ticket = PositionGetTicket(PositionsTotal() - 1);
      if (PositionSelectByTicket(ticket)) {
         double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
         double currentPrice = PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY ? SymbolInfoDouble(_Symbol, SYMBOL_BID) : SymbolInfoDouble(_Symbol, SYMBOL_ASK);
         double profit = PositionGetDouble(POSITION_PROFIT);
         
         if (profit < 0 && MathAbs(openPrice - currentPrice) / _Point >= Inp_Grid_${grid.id}_Step) {
            double newLot = PositionGetDouble(POSITION_VOLUME) * Inp_Grid_${grid.id}_Multiplier;
            if (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) {
               trade.Buy(newLot);
            } else {
               trade.Sell(newLot);
            }
         }
      }
   }
`;
  }

  code += `  }
//+------------------------------------------------------------------+
//| News Filter Stub Function                                        |
//| Replace this logic with your ForexFactory/Economic Calendar code |
//+------------------------------------------------------------------+
bool CheckNews(int minsBefore, int minsAfter) {
   // To be implemented by user or connected via WebRequest
   // Returns true if there is High Impact news currently.
   return false;
}
`;

  return code;
}
