export function generateIndMQL5(nodes, edges, projectName) {
  const name = projectName.replace(/[^a-zA-Z0-9_]/g, '_');
  let code = `//+------------------------------------------------------------------+
//|                                                      ${name}.mq5 |
//|                        Generated by AI EA Builder (Indicator)    |
//+------------------------------------------------------------------+
#property copyright "AI EA Builder"
#property link      "https://github.com"
#property version   "1.00"
#property indicator_chart_window
`;

  const buffers = nodes.filter(n => n.type === 'buffer');
  
  if (buffers.length > 0) {
     code += `#property indicator_buffers ${buffers.length}\n`;
     code += `#property indicator_plots ${buffers.length}\n`;
  } else {
     code += `#property indicator_buffers 1\n`;
     code += `#property indicator_plots 1\n`;
  }

  // Define properties for each buffer
  buffers.forEach((b, idx) => {
      code += `\n//--- plot Buffer${b.data.bufferId}\n`;
      code += `#property indicator_label${idx + 1}  "Buffer ${b.data.bufferId}"\n`;
      code += `#property indicator_type${idx + 1}   ${b.data.style || 'DRAW_LINE'}\n`;
      code += `#property indicator_color${idx + 1}  ${b.data.color || 'clrRed'}\n`;
      code += `#property indicator_style${idx + 1}  STYLE_SOLID\n`;
      code += `#property indicator_width${idx + 1}  1\n`;
  });

  code += `\n//--- indicator buffers\n`;
  buffers.forEach(b => {
      code += `double         Buffer${b.data.bufferId}[];\n`;
  });

  const indicators = nodes.filter(n => n.type === 'indicator');
  
  // Inputs
  indicators.forEach(ind => {
    code += `\n//--- ${ind.data.name} Settings\n`;
    const params = ind.data.params || {};
    Object.keys(params).forEach(k => {
      const val = params[k];
      const type = typeof val === 'number' ? (val % 1 !== 0 ? 'double' : 'int') : 'string';
      const safeVal = type === 'string' ? `"${val}"` : val;
      code += `input ${type} Inp_${ind.id}_${k} = ${safeVal}; // ${k}\n`;
    });
  });

  code += `\n//--- Indicator Handles\n`;
  indicators.forEach(ind => {
    code += `int handle_${ind.id};\n`;
    code += `double buffer_${ind.id}[];\n`;
  });

  // OnInit
  code += `
//+------------------------------------------------------------------+
//| Custom indicator initialization function                         |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- indicator buffers mapping
`;
  
  buffers.forEach((b, idx) => {
     code += `   SetIndexBuffer(${idx}, Buffer${b.data.bufferId}, INDICATOR_DATA);\n`;
  });

  indicators.forEach(ind => {
    const isCustom = ind.data.isCustom;
    if (isCustom) {
      let args = `Symbol(), PERIOD_CURRENT`;
      const params = ind.data.params || {};
      Object.keys(params).forEach(k => {
         args += `, Inp_${ind.id}_${k}`;
      });
      code += `   handle_${ind.id} = iCustom(${args});\n`;
    } else {
      let args = `Symbol(), PERIOD_CURRENT`;
      const params = ind.data.params || {};
      Object.keys(params).forEach(k => {
         args += `, Inp_${ind.id}_${k}`;
      });
      // Simplified: Just use iMA/iRSI as placeholder if standard indicator
      code += `   handle_${ind.id} = iMA(${args}); // Replace with actual built-in mapping if needed\n`;
    }
    code += `   ArraySetAsSeries(buffer_${ind.id}, true);\n`;
  });

  code += `
   return(INIT_SUCCEEDED);
}
`;

  // OnCalculate
  code += `
//+------------------------------------------------------------------+
//| Custom indicator iteration function                              |
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   if(rates_total < 10) return(0);
   int limit = rates_total - prev_calculated;
   if(prev_calculated > 0) limit++;
   else limit = rates_total - 1;

`;

  indicators.forEach(ind => {
      code += `   CopyBuffer(handle_${ind.id}, 0, 0, limit, buffer_${ind.id});\n`;
  });

  code += `\n   for(int i=0; i<limit; i++) {\n`;
  
  // Logic linking
  buffers.forEach(b => {
      // Find what connects to this buffer
      const connectedEdge = edges.find(e => e.target === b.id);
      if (connectedEdge) {
          const sourceId = connectedEdge.source;
          // If it's directly connected to an indicator
          const sourceInd = indicators.find(i => i.id === sourceId);
          if (sourceInd) {
              code += `      Buffer${b.data.bufferId}[i] = buffer_${sourceInd.id}[i];\n`;
          } else {
             // For logic nodes (Math operations), this would require parsing the AST of nodes.
             // For this basic MVP, we just assign 0.
             code += `      Buffer${b.data.bufferId}[i] = 0.0; // Needs Math Parsing\n`;
          }
      }
  });

  code += `   }
   return(rates_total);
}
//+------------------------------------------------------------------+
`;

  return code;
}
